### ISSUE TITLE
Muxed WebM Opus audio file is not seekable

### ISSUE THREAD

**Issue by AshleyScirra** [davedoesdev/webm-muxer.js#1]
Thanks for your work on providing a WebM muxer for WebCodecs!

I've been prototyping a WebM Opus transcoder with this and it looks like the resulting WebM Opus file is not seekable in any of the playback software I've tried.

Repro code: [webMOpusTranscoder.zip](https://github.com/davedoesdev/webm-muxer.js/files/6836760/webMOpusTranscoder.zip) (just host on a local web server or something)
Note this is developed against Chrome Canary 94.0.4579.0 with Experimental Web Platform features enabled, so there may be some API differences to different Chrome versions. I also work on Windows 10 x64.

You'll need a sample audio file as well, which can be any reasonably long audio file the browser can decode - try this if you need one: https://www.dropbox.com/s/jnw8cyn75x67mlk/oglseby7.wav?dl=0
When you open the repro HTML file, drag and drop an audio file to transcode into the dashed box. Check the browser console; it will log some messages about what it's doing (which involves using Web Audio to decode the file; WebCodecs to encode it to Opus; and then muxes to WebM) and then invoke a download of a file named audio.webm. The end result is the dropped audio file is transcoded to WebM Opus.

The produced WebM file plays fine, but does not appear to be seekable. I've tried Windows 10's 'Films & TV' app (the default), Chrome, MPC-HC, and VLC. I don't know much about the WebM format but I believe there is extra data required to be added by the muxer to enable seeking. It would be great if that could be supported.

**Comment by davedoesdev** [comment]
@AshleyScirra thanks for picking this up. I'll try to take a look in the next couple of days.

**Comment by davedoesdev** [comment]
OK I modified your program slightly for older Chrome (91.0.4472.114 Linux). This produces a seekable WebM file:

```js

import * as Utils from "./utils.js"

//////////////////////////////////////
// Drag and drop handling
const dropElem = document.getElementById("dropzone");
dropElem.addEventListener("dragover", e => e.preventDefault());
dropElem.addEventListener("dragenter", e => dropElem.classList.add("hover"));
dropElem.addEventListener("dragleave", e => dropElem.classList.remove("hover"));
dropElem.addEventListener("drop", e =>
{
	e.preventDefault();
	e.stopPropagation();
	
	dropElem.classList.remove("hover");
	
	TranscodeAudio(e.dataTransfer.files[0]);
});

//////////////////////////////////////
// WebM worker
const muxedDataChunks = [];
let startResolve = null;
const startPromise = new Promise(resolve => startResolve = resolve);

const webMWorker = new Worker("./muxer/webm-worker.js");
webMWorker.onerror = (err => console.error("[WebM worker] Error: ", err));
webMWorker.onmessage = (e =>
{
	const msg = e.data;
	switch (msg.type) {
	case "exit":
		console.log("[Message from WebM worker] Exit");
		OnWebMMuxerDone();
		break;
	case "start-stream":
		startResolve();		// resolve startPromise
		break;
	case "muxed-data":
		console.log("[Message from WebM worker] Received muxed data");
		muxedDataChunks.push(msg.data);
		break;
	case "error":
		console.error("[Message from WebM worker] Error: ", msg.detail);
		break;
	}
});

//////////////////////////////////////
// Transcoding
// Create AudioContext just for decoding
const audioContext = new AudioContext({
	sampleRate: 48000		// match Opus sample rate
});

// Create AudioEncoder
const audioEncoder = new AudioEncoder({
	output: AudioEncoderOutput,
	error: AudioEncoderError
});

async function TranscodeAudio(file)
{
	// Use browser to demux and decode audio data to Float32Arrays
	const fileArrayBuffer = await file.arrayBuffer();
	const audioBuffer = await audioContext.decodeAudioData(fileArrayBuffer);
	
	// Dump channels in to one big Float32Array in planar arrangement
	const planarData = new Float32Array(audioBuffer.length * audioBuffer.numberOfChannels);
	for (let i = 0; i < audioBuffer.numberOfChannels; ++i)
	{
		planarData.set(audioBuffer.getChannelData(i), i * audioBuffer.length);
	}
	
	// Start up WebM encoder worker
	webMWorker.postMessage({
		type: "start",
		webm_metadata: {
			max_segment_duration: BigInt(1000000000),
			audio: {
				sample_rate: audioBuffer.sampleRate,
				channels: audioBuffer.numberOfChannels,
				//bit_depth: 32,		// ?
				codec_id: "A_OPUS"
			}
		}
	});
	
	// Wait for "start-stream" message from WebM encoder
	await startPromise;
	
	// Configure audio encoder for this audio track
	audioEncoder.configure({
		codec: "opus",
		sampleRate: audioBuffer.sampleRate,
		numberOfChannels: audioBuffer.numberOfChannels
	});
	
	// Create an AudioData for the entire audio content
	const audioData = new AudioFrame({
		/*format: "FLTP",		// planar float32 data
		sampleRate: audioBuffer.sampleRate,
		numberOfFrames: audioBuffer.length,
		numberOfChannels: audioBuffer.numberOfChannels,*/
		timestamp: 0,
		//data: planarData
        buffer: audioBuffer
	});
	
	// Encode it then finish WebM worker
	console.log("Encoding...");
	
	audioEncoder.encode(audioData);
	await audioEncoder.flush();
	
	console.log("Finished encoding, finishing muxer...");
	
	webMWorker.postMessage({ type: 'end' });
}

function AudioEncoderOutput(chunk, metadata)
{
	//console.log("Audio encoder output received");
	
	// Copy out encoded audio data and send it to WebM muxer
	//const data = new ArrayBuffer(chunk.byteLength);
    //chunk.copyTo(data);
    const data = chunk.data.slice(0, chunk.byteLength);
	
	webMWorker.postMessage({
		type: "audio-data",
		timestamp: chunk.timestamp,
		duration: chunk.duration,		// not sure Canary is setting chunk.duration...
		is_key: true,
		data
	}, /* transfer */ [data]);
}

function AudioEncoderError(err)
{
	console.error("Audio encoder error: ", err);
}

function OnWebMMuxerDone()
{
	// Create blob of all muxed data chunks and download it
	const blob = new Blob(muxedDataChunks, { type: "audio/webm" });
	Utils.Download("audio.webm", URL.createObjectURL(blob));
}
```

**Comment by davedoesdev** [comment]
Ah interesting! It's seekable using the built-in Ubuntu player (Totem) but not using VLC!

**Comment by davedoesdev** [comment]
OK this might give us a clue: https://bugs.chromium.org/p/chromium/issues/detail?id=642012
Although it's for MediaRecorder, it does say that there would need to be a cues section in the generated WebM file. I'm not sure whether AudioEncoder adds that.

**Comment by davedoesdev** [comment]
Ah

https://github.com/davedoesdev/webm-tools/blob/707b903f622ddc3585c2f3090c42936f45fa2d17/shared/webm_chunk_writer.h#L49

I'm using WebM tools live muxer and chunk writer so as the comments indicate it's not going to be seekable.
Totem is probably using a hack similar to the one suggested in the chromium bug above (read all the data in first).

This would need an alternative mode of encoding that doesn't use the WebM tools code. I'm not sure I have time to do that. Perhaps I should rename this repo webm-live-muxer.js as my ultimate aim is to use it to stream to YouTube via HLS.

Another possibility is to port https://github.com/legokichi/ts-ebml or https://github.com/node-ebml/node-ebml to work in the browser. They can convert an unseekable WebM (such as MediaRecorder, or webm-muxer.js, produces) into a seekable one.

@AshleyScirra let me know what you think.

**Comment by davedoesdev** [comment]
Ooh, this comment:

https://github.com/muaz-khan/RecordRTC/issues/147#issuecomment-459954869

suggests that RecordRTC uses https://www.webrtc-experiment.com/EBML.js to get a seekable file.

I wonder if it would work for your use case too @AshleyScirra ?

Code is here: https://recordrtc.org/RecordRTC.js.html#line1903

**Comment by davedoesdev** [comment]
This confirms I'm on the right lines here: https://stackoverflow.com/questions/66480784/not-able-to-create-seekable-video-blobs-from-mediarecorder-using-ebml-js-media

I'm not sure whether this should be part of webm-muxer.js or another demo?

**Comment by AshleyScirra** [comment]
Thanks for looking in to this. It seems reasonable to use a post-processing step that modifies the output WebM to add seek information. While a transcoder knows in advance the size of the media it's working with so presumably could add seek information in advance, doing it as a post-process step covers both transcoding and unknown-length cases like live streaming and MediaRecorder (which we also use in some other places... so it would be handy to cover that too). So it seems like a more general-purpose solution, and not supporting that in this project would be a fair conclusion.

**Comment by davedoesdev** [comment]
I'll add a demo to show post-processing

**Comment by davedoesdev** [comment]
Demo extended with recording and conversion to seekable format using EBML.js
README updated

**Comment by guest271314** [comment]
Note, `AudioData` replaced the deprecated `AudioFrame`, `'f32-planar'` replaced `'FLTP'` `format` in latest Chromium though the specification has not been updated to reflect that change.

**Comment by davedoesdev** [comment]
@guest271314 thanks. I'll work on updating to `AudioData` when I get time - hopefully later this week.

**Comment by davedoesdev** [comment]
Updated to `AudioData` for unencoded PCM in e2a6875595e5c7bf131610adde641aad15143992
