### ISSUE TITLE
Limit buffered data

### ISSUE THREAD

**Issue by davedoesdev** [davedoesdev/webm-muxer.js#14]
`webm-worker.js` operates audio and video queues to help with synchronisation. If one of audio or video slows down (or even stops) then the other will end up queued until EOS. For video especially this can take up a lot of memory.

Have an option for the application to specify a limit on the amount of data that can be held in each queue.

**Comment by sashazxtt** [comment]
I've refactored the `end` code into a function that is called from both places (`end` and `send_msgs()`) and it appears to be working normally - at least in the case where my audio stops abruptly.

**Comment by davedoesdev** [comment]
Yes that should work. Once I have a branch with my changes, we can compare and see whether they're enough for your use cases.

**Comment by davedoesdev** [comment]
The `shifted-video` branch https://github.com/davedoesdev/webm-muxer.js/tree/shifted-video has options for this issue.

Setting `audio_queue_limit`and/or `video_queue_limit` will ensure a limit is placed on the amount of data buffered. So if audio stops, for example, video would continue to be sent to the muxer.

There's also `use_audio_timestamps`, which should be set if audio is expected to be intermittent.

**Comment by davedoesdev** [comment]
Now on main branch
