### ISSUE TITLE
[Feature request] Audio only version to replace MediaRecorder

### ISSUE THREAD

**Issue by guest271314** [davedoesdev/webm-muxer.js#17]
Chromium `MediaRecorder` has several issues:

- No durationm set by default
- Last 1-2 seconds of audio can be clipped in resulting WebM file
- `ondataavailable` event handler taking substantial time to fire and potentially retaining references to objects which cause issues in other API's https://bugs.chromium.org/p/chromium/issues/detail?id=1253143, https://groups.google.com/a/chromium.org/g/media-dev/c/vPswattW0xU

I am currently creating `AudioData` from raw PCM input and using `MediaStreamTrackGenerator` in a `MediaStream` to pass to `MediaRecorder`.

**Comment by davedoesdev** [comment]
@guest271314 it should support audio only already, although I admit I haven't tested it much with audio only.
What have you tried so far? You should just be able to:

- Only create a single Web Worker running `encoder-worker.js` for audio.
- When you send the `start` message to the Web Worker running `webm-worker.js`, only send `audio` in `webm_metadata`.

Please let me know if that doesn't work.

**Comment by guest271314** [comment]
> What have you tried so far? 

I have not tried, yet. I need to decouple `navigator.mediaDevices.getUserMedia()` and `MediaSoure()` code from demo.js. I have a `ReadableStream` from `MediaStreamTrackProcessor`. Ideally the goal is to not use `Worker`, as I would need to stream from an aribitrary orgin to an embedded `<iframe>` for my use case https://github.com/guest271314/captureSystemAudio/blob/master/native_messaging/capture_system_audio/audioStream.js. I should be able to store all of the code in Chromium Sources > Snippets. I will try to create an audio only example without `getUserMedia()`.

**Comment by guest271314** [comment]
I am basically trying to strip out all video parts and get the audio parts into a single minified block of code.

**Comment by davedoesdev** [comment]
Let me if there's any restructuring in the main code that would make things like this easier.

**Comment by guest271314** [comment]
It will take some time to remove video parts, and web workers from the code and merge all into a single file. You know what the audio parts and video parts are now. If you find the time perhaps you can create audio and video branches, then remove the web worker code parts. I will be doing the same in tandem without knowing all of the discrete parts until I read them.

**Comment by sashazxtt** [comment]
I was able to create audio-only files, but admittedly I've not been testing that too much. I just don't create the video encoder.

**Comment by guest271314** [comment]
I started on this here https://github.com/guest271314/webm-muxer.js/tree/audio-only.

Adjustments other than removing video references:

demo.js:

- Define `writer` outside of `start_el` click handler;
- Call `writer.finish()` is `stop_el` click handler to avoid  .crswap files and camera.webm having size 0 due to `close()` not being called.

Question:

I reduced `send_msgs` https://github.com/guest271314/webm-muxer.js/blob/main/webm-worker.js#L107-L120 to

```
function send_msgs(opts) {
    if (!metadata.video) {
        while (queued_audio.length > 0) {
            send_msg(queued_audio.shift());
        }
        return;
    }

    while (queued_audio.length > 0) {
        const atimestamp = get_audio_ts(queued_audio[0]);
        send_msg(set_audio_ts(queued_audio.shift(), atimestamp));
    }

    while (queued_audio.length > opts.audio_queue_limit) {
        const msg = queued_audio.shift();
        if ((queued_audio.length === opts.audio_queue_limit) &&
            (++audio_msgs_since_last_cluster > opts.audio_queue_limit)) {
            msg.new_cluster = true;
            audio_msgs_since_last_cluster = 0;
        }
        const atimestamp = get_audio_ts(msg);
        send_msg(set_audio_ts(msg, atimestamp));
    }
}

```

I tried with either of the first two `while` function. Either appear to work. Are both (the top two) `while` loops necessary?

**Comment by davedoesdev** [comment]
Thanks for looking at this. It was on my list to look at but I haven't got round to it, so I appreciate the work you've done.

The first `while` loop is just there to shortcut things when there's no video, I assumed it would be faster in that case. It's probably unnecessary and maybe doesn't speed things up?

**Comment by guest271314** [comment]
I sisn't notice any difference re speed. I was not evaluating speed either though. The calls are slightly different

```
send_msg(queued_audio.shift());
```

and 

```
const atimestamp = get_audio_ts(queued_audio[0]);
send_msg(set_audio_ts(queued_audio.shift(), atimestamp));
```

Can the former `while` loop simply be removed?

**Comment by guest271314** [comment]
I could not tell the difference re speed. I wasn't measuring speed either though. I am just trying to remove all non-essential code before I try to merge all of the code into one file.

**Comment by davedoesdev** [comment]
Yes I believe so (I assume you've removed all the video code)

**Comment by davedoesdev** [comment]
@guest271314 OK finally getting back to this. (a) Is this still a thing? (b) Where did you get to?

**Comment by guest271314** [comment]
This is the farthest I have gotten https://github.com/guest271314/webm-muxer.js/tree/audio-only. I would still prefer to replace `MediaRecorder` in my own code. I'll close this.

**Comment by guest271314** [comment]
If I understand the flow correctly `'./encoder-worker.js'` passes data to `'./webm-worker.js'` where `'./webm-muxer.js'` is created which muxes the media input content?

Did you begin the original code using multiple Worker instances?

**Comment by davedoesdev** [comment]
Yes and yes.

The first version of the demo: https://github.com/davedoesdev/webm-muxer.js/tree/b6b32b2d64ad85640ef75e4d54b579e185a01811 used multiple Workers

**Comment by guest271314** [comment]
demo.html with all script content in the single file https://github.com/guest271314/webm-muxer.js/blob/audio-only/demo.html. 

I initially tried to substitute `MessageChannel` for `Worker` contexts. I will probably try that again, then substitute Streams API for `MessageChannel`, then remove video parts from `webm_muxer.cc`. I think the main scripts have been updaed since I forked your repository and created the `audio-only` branch. Kindly review to check if your code is working as expected.

**Comment by davedoesdev** [comment]
I don't think you need `last_key_frame`.

In `send_msgs` you can remove a lot since the first test will always be true.

Same with `send_metadata` tests for `metadata.audio`.

Don't need video element.

Not tried it yet.

**Comment by guest271314** [comment]
The main obstacle is the nested, cascading `Worker`s. That is how you first committed so we can't do anything about that but undo it. Eventually there should be a flow chart that consists of a single TransformStream that traverses the current discrete `Worker` code and is substrituted therefor.

**Comment by davedoesdev** [comment]
Seems to record the tone fine
