### ISSUE TITLE
Webm dash manifest / Recording chunks

### ISSUE THREAD

**Issue by happylinks** [davedoesdev/webm-muxer.js#20]
Hey there,

Thanks for this repo, learning a lot about webcodecs and webm muxing.

My goal is go create a (properly seekable) webm dash manifest in the client that I can upload to the server while recording, chunk by chunk.
When finished recording this would mean I have a streamable video on a server.

I saw that webm_dash_manifest is in webm-tools, which is included in this repo, could that maybe help? My goal would be to mux the initialization file, then the chunk files, then at the end describe them in a dash manifest xml that's playable.

Any advice/pointers would be great!

Thanks,
Michiel

**Comment by davedoesdev** [comment]
Hi Michiel

https://github.com/davedoesdev/streamana

Has DASH support, is there anything you can use from there?

David

**Comment by happylinks** [comment]
Hey Dave,

Yes that looks exactly like what I need. I don't need it for live-streaming, but I can definitely tweak it to just send the manifest once at the end instead of during recording. The chunking seems perfect though.

Thanks a lot for the repo! Will bug you with more questions if I have them :)

Michiel
