### ISSUE TITLE
chroma not defined in demo.js

### ISSUE THREAD

**Issue by onthegit** [davedoesdev/webm-muxer.js#22]
Hello, chroma is not defined in demo.js. Supposed to be chroma_el.value?

https://github.com/davedoesdev/webm-muxer.js/blob/97a2c52442dcc8b4a8ee3eb5e98351f35d6d3a9f/demo.js#L49
https://github.com/davedoesdev/webm-muxer.js/blob/97a2c52442dcc8b4a8ee3eb5e98351f35d6d3a9f/demo.js#L64
https://github.com/davedoesdev/webm-muxer.js/blob/97a2c52442dcc8b4a8ee3eb5e98351f35d6d3a9f/demo.js#L65

**Comment by davedoesdev** [comment]
@onthegit yes you're right, and thanks! The strange thing is my Chrome doesn't show the error. I'll investigate.

**Comment by davedoesdev** [comment]
`chroma` seems to be defined as the element:

```
>chroma
<input type=​"hidden" id=​"chroma">​
```

**Comment by davedoesdev** [comment]
I guess by way of having the `id` set to `"chroma"`

**Comment by davedoesdev** [comment]
https://stackoverflow.com/questions/13684295/id-attribute-on-form-element-results-in-global-variable

That happens normally but I think your change is correct - thanks again.
I've pushed the change.
