### ISSUE TITLE
Resulting Video is not playable

### ISSUE THREAD

**Issue by onthegit** [davedoesdev/webm-muxer.js#23]
Hello,
I tried to create webm video file, however the resulting file is not playable. Errors are not shown in the console except for "End of input" that comes from webm-muxer.js

ffprobe shows this output:
```
Input #0, matroska,webm, from 'test.webm':
  Metadata:
    encoder         : libwebm-0.3.0.0
duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv), 506x284, SAR 1:1 DAR 253:142, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
[STREAM]
index=0
codec_name=vp9
codec_long_name=Google VP9
profile=Profile 0
codec_type=video
codec_time_base=1/60
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=506
height=284
coded_width=506
coded_height=284
has_b_frames=0
sample_aspect_ratio=1:1
display_aspect_ratio=253:142
pix_fmt=yuv420p
level=-99
color_range=tv
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=unspecified
field_order=unknown
timecode=N/A
refs=1
id=N/A
r_frame_rate=60/1
avg_frame_rate=60/1
time_base=1/1000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:language=eng
[/STREAM]

```

It looks like duration is not set??

When playing the video in Chrome it just plays 1 frame, the first and some random frame. The resulting size of 6 seconds  video is 2.3mb.

**Comment by davedoesdev** [comment]
Hmm, another duration issue. Perhaps there is something in this after all.
How did you drive the muxer to create the file?

**Comment by davedoesdev** [comment]
The demo works for me, does it work for you?

**Comment by onthegit** [comment]
@davedoesdev  could you tell me where is the unpacked code of webm-muxer.js ? It is not library.js? because it does not have the "End of input" console.log message. Thanks.

**Comment by onthegit** [comment]
I managed to get playable webm video, the error was on my side having placed milliseconds instead of microseconds for timestamp and duration of video frame.  I fixed that, however, now the webm video is not seekable and the duration is still n/a.

**Comment by onthegit** [comment]
Upon investingating it looks like the EBML.reader is returning 0 duration?
https://github.com/davedoesdev/webm-muxer.js/blob/71d73c0f408cae8499ca2ae23bb5166bbd308ca3/webm-writer.js#L54

**Comment by davedoesdev** [comment]
I can't repro that in the demo https://rawgit-now.netlify.app/davedoesdev/webm-muxer.js/main/demo.html
To rule out the underlying platform, do files the demo records and saves have the correct durations for you?

**Comment by onthegit** [comment]
@davedoesdev Thanks for your replies. I ended up manually setting duration based on calculation of processed frames.
