### ISSUE TITLE
Demuxing

### ISSUE THREAD

**Issue by onthegit** [davedoesdev/webm-muxer.js#25]
Can webm files be demuxed into chunked data, which then can be fed into VideoDecoder?

**Comment by davedoesdev** [comment]
No, sorry. I'm happy to leave this issue open in case anyone wants to pick this up.

I'm not sure if there's code in libwebm or webm-tools to do demux easily, however.

**Comment by guest271314** [comment]
> Can webm files be demuxed into chunked data, which then can be fed into VideoDecoder?

Yes, that is possible. You can serialize the data to JSON. See https://github.com/guest271314/webcodecs/blob/main/serialize-to-json-deserialize-json-to-encodedaudiochunk-decode.js and https://github.com/guest271314/webcodecs/blob/main/deserialize-json-to-encodedaudiochunk-decode.js.

**Comment by davedoesdev** [comment]
Yeah of course, you can use WebCodecs to do it (the Decoder classes).

**Comment by onthegit** [comment]
> > Can webm files be demuxed into chunked data, which then can be fed into VideoDecoder?
> 
> Yes, that is possible. You can serialize the data to JSON. See https://github.com/guest271314/webcodecs/blob/main/serialize-to-json-deserialize-json-to-encodedaudiochunk-decode.js and https://github.com/guest271314/webcodecs/blob/main/deserialize-json-to-encodedaudiochunk-decode.js.

Hello, thanks for the reply, but from quick look at the code, it will not work in workers and it requires fetching the entire file. Fetching the entire file is prohibitive for large files (whether video or audio).

**Comment by onthegit** [comment]
The better option will be to feed bytes, and the structure is parsed on the fiy like what gpac/mp4box.js does

**Comment by guest271314** [comment]
@onthegit Why won't the code work in workers? Did you try? No, the entire file does not have to be fetched. An example of streaming video frames without using any Web API codec parser, written originally for Firefox https://plnkr.co/plunk/4Tb91b, Chromium version https://plnkr.co/plunk/gCjYSt.

**Comment by guest271314** [comment]
See also rapid_video_painter.html at https://github.com/chcunningham/wc-talk.

**Comment by guest271314** [comment]
For VP8 frames see https://github.com/dominikhlbg/vp8-webm-javascript-decoder, which I used to create https://github.com/guest271314/screenshot.
