### ISSUE TITLE
Breaks for MediaStreamTrack from HTMLMediaElement.captureStream()

### ISSUE THREAD

**Issue by guest271314** [davedoesdev/webm-muxer.js#31]
Object returned from `getSettings()` method of `MediaStreamTrack` from `HTMLMediaElement.captureStream()` does not include `channelCount`, only `deviceId` and `sampleSize`. `MediaStreamTrack.channelCount` is `undefined`, and Web Audio API `MediaStreamAudioSourceNode` `channelCount` is always set to `2`, does not reflect the actual channel count of the underlying `MediaStreamTrack`.

https://github.com/davedoesdev/webm-muxer.js/blob/375cc63f5bd940303037026347ff141b2ee2281f/demo.js#L140

One approach to get the accurate channel count is create a `MediaStreamTrckProcessor` to read one frame, get `numberOfChannels` from `AudioData`

      const getChannelCount = async(track) => {
        const processor = new MediaStreamTrackProcessor({track});
        const reader = processor.readable.getReader();
        const { numberOfChannels } = (await reader.read()).value;
        try {
          await reader.cancel();
          await reader.closed;
        } catch(e) {
          console.log(e);
        }
        return numberOfChannels;
      }

**Comment by davedoesdev** [comment]
Thanks, I can confirm `channelCount` is always 2, very helpful API that :)

**Comment by guest271314** [comment]
@davedoesdev I filed a Web Audio API issue re this. If you are so inclined perhaps you can post your test results there and describe how the incorrect value for `channelCount` is problematic for your code.

I encountered this while testing concatenating all encoded audio from WebCodecs `AudioEncoder` to a single file with the minimal header instructions necessary to play back the file with Media Source Extensions `appendEncodedChunks()`. During preliminary testing the file size is less than Opus in WebM produced by `MediaRecorder`, for a 4:14 audio file captured with `captureStream()` the WebM file is 3196093 bytes, the header plus `ArrayBuffer` from `AudioData` is 
3184702 bytes,  thus we do not really need to write the Opus packs to a WebM container. It would be helpful for independent testing with greater during input. Let me know if you are interested.

**Comment by davedoesdev** [comment]
Yeah sorry I don't have time to do that.

Is the WebAudio API issue https://github.com/WebAudio/web-audio-api/issues/2389 ?

**Comment by guest271314** [comment]
No. That is the other part of `channelCount` issues in Web Audio API. https://github.com/WebAudio/web-audio-api/issues/2496. The core issue is `getSettings()` does not work. However, W3C banned me from filing issues in their repositories.

> Yeah sorry I don't have time to do that.

If you find the time, let me know. I prefer independent testing to verify results. I improved the encoding part. I am relatively certain the encoding part consistently produces a file of less size than writing to a WebM container. This is the initial version of the playback part https://plnkr.co/edit/cAbZqVXfzZMFOaxL.

**Comment by guest271314** [comment]
> Yeah sorry I don't have time to do that.

FWIW, Not much time is required to test. I already wrote the code that saves both `MediaRecorder` result and `AudioEncoder` configuration with `'opus'` packets. All that is required is to verify on a different machine that the file produced by writing metadata, offsets, and audio packs is less than the WebM file produced by `MediaRecorder`.

**Comment by guest271314** [comment]
@davedoesdev FWIW this is the source code to write configuration and `EncodedAudioChunk`s to a single file, and play back that single file using Media Source Extensions https://github.com/guest271314/WebCodecsOpusRecorder. So far in all of the tests I have run the file is less size compared to encoding Opus packets in a WebM container.

**Comment by guest271314** [comment]
I don't think `channelCount`  Web Audio API or `getSettings()` from Media Capture and Streams will be fixed anytime soon. Closing this.
