### ISSUE TITLE
Project obsolete?

### ISSUE THREAD

**Issue by Vanilagy** [davedoesdev/webm-muxer.js#35]
Hi,

I recently implemented my own take on WebM muxing which you can find here: https://github.com/Vanilagy/webm-muxer
It muxes both video and audio, and is entirely written in TypeScript (no large wasm files needed)

**Comment by davedoesdev** [comment]
Your project looks pretty nice. I'll leave this issue open so to remind me to add a pointer to it when I get time. Thanks!

**Comment by Vanilagy** [comment]
Awesome! And thanks.

**Comment by davedoesdev** [comment]
Pointer added in https://github.com/davedoesdev/webm-muxer.js/commit/7e1a30b83792099121e90a774cdc16ad60ddff69
Thanks for doing a non-wasm version!

**Comment by Vanilagy** [comment]
<3

**Comment by Vanilagy** [comment]
Thanks for the shoutout!
